language: php

sudo: true

addons:
  firefox: "47.0.1"
  postgresql: "9.4"
  apt:
    packages:
      - openjdk-8-jdk
      - java-common

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.0
 - 7.1

env:
 global:
 - MOODLE_BRANCH=MOODLE_35_STABLE
  - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
 matrix:
  - DB=pgsql
  - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - nvm ls-remote
  - nvm install v8.9
  - nvm use v8.9
  - nvm alias default v8.9.4
  - node --version
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install
 
script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt --tasks amd
  - moodle-plugin-ci grunt --tasks gherkinlint
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
